### ISSUE TITLE
[Feature Request] Support for Google Fonts Early Access. (Noto Sans family)

### ISSUE THREAD

**Issue by evenchange4** [KyleAMathews/typefaces#11]
Thanks for the awesome works! 

I want to use `Noto Snas TC` with my project. Is there any plans to add the [Google Fonts Early Access](https://fonts.google.com/earlyaccess) to this project?

**Comment by KyleAMathews** [comment]
We're leveraging @majodev's awesome google-webfonts-helper project to automate creating packages. From this issue — it looks like they haven't added support for early access fonts yet https://github.com/majodev/google-webfonts-helper/issues/13

But in the meantime, happy to add individual fonts as people need them. Created the font and will be publishing it soon. Let me know if it turned out right.
