### ISSUE TITLE
[Font Request] Public Sans

### ISSUE THREAD

**Issue by jeffgreco** [KyleAMathews/typefaces#122]
Really nice redraw of Libre Franklin by 18F: https://github.com/uswds/public-sans

**Comment by grubersjoe** [comment]
I've added a package for Public Sans: https://www.npmjs.com/package/typeface-public-sans

If possible the package could also be integrated here.

**Comment by KyleAMathews** [comment]
@grubersjoe nice! Yeah putting together a package manually can definitely work. I _do_ have a script for creating packages from fontsquirrel and since the typeface is there — I could take over the package if you don't want to keep maintaining it https://www.fontsquirrel.com/fonts/public-sans

But not too big of deal to me either if you want to keep it.

**Comment by grubersjoe** [comment]
I'm fine with you taking over the package. How does that work? Should I simply add your user to the package like this and remove myself afterwards?

```
npm owner add kylemathews
```

**Comment by grubersjoe** [comment]
Alright, I've added you!

**Comment by KyleAMathews** [comment]
Published new version, thanks!
