### ISSUE TITLE
Update Montserrat

### ISSUE THREAD

**Issue by nthtran** [KyleAMathews/typefaces#13]
Google now has [other styles](https://fonts.google.com/specimen/Montserrat) for Montserrat but we still have only Regular and Bold.

**Comment by KyleAMathews** [comment]
Thanks for pointing this out! Both because I'm super happy Montserrat has italics now as it's one of my favorite fonts but also I hadn't realized how out-of-date the API info we're using from https://github.com/majodev/google-webfonts-helper is. I'd been using their hosted Heroku version which only had the bold and regular fonts not even the other non-italic weights. But thankfully it's easy to run locally so I installed that and just pushed an updated Montserrat package to NPM with all the weights and styles on Google Fonts.

A bit later I'll rerun all Google Fonts to get whatever other updates we're missing.

**Comment by nthtran** [comment]
Thanks for the quick update! It's super awesome what you're doing here.

**Comment by lapo-luchini** [comment]
[typeface-eb-garamond](https://fonts.google.com/specimen/EB+Garamond) seems to be missing italic and different weights too.

**Comment by KyleAMathews** [comment]
@lapo-luchini thanks for the bug report! Just regenerated a bunch of google font packages including eb-garamond. Lemme know if the new version is working for you.
