### ISSUE TITLE
[Font Request] Source Serif Italic

### ISSUE THREAD

**Issue by Brixy** [KyleAMathews/typefaces#80]
Hi Kyle!

At last italics were added to _Source Serif._ Beautiful! (Variable fonts are also available.)

https://github.com/adobe-fonts/source-serif-pro/releases

It would be great if you could add them.

Thank you very much!

**Comment by KyleAMathews** [comment]
We pull Source Serif from Google fonts https://fonts.google.com/?query=source+ser where it doesn't seem they've updated yet.

**Comment by lukebennett88** [comment]
Hi @KyleAMathews, I noticed you mentioned in a different issue that you pull some of the fonts for Typefaces from Font Squirrel. I just checked and it looks like _they_ have the updated italics, but Google still does not.

Would you consider changing to Font Squirrel for this font? It has been several months now since the italics for Source Serif Pro were released, and Google Fonts still haven't updated them.

**Comment by KyleAMathews** [comment]
Great idea! Published typeface-source-serif-pro with the files from fontsquirrel. Upgrade to get those sweet sweet italics.

**Comment by joernroeder** [comment]
@KyleAMathews did you include the italic versions at some point? the current version lacks them.
Another opportunity would be to pull directly from https://github.com/adobe-fonts/source-serif-pro
I need the italic versions for a project I am currently building, please let me know how I can help to get them integrated quickly.

**Comment by KyleAMathews** [comment]
yeah, looks like when I update fonts from google fonts it overwrote the font squirrel publish 🙄 — I'm updating from google fonts again & then I'll update from fontsquirrel again to get the italics out.

**Comment by KyleAMathews** [comment]
ok `typeface-source-sans-pro@1.1.5` has italics again
